# Netlify Configuration for Dr. Mukesh Gautam Website

[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/sitemap"
  to = "/sitemap.xml"
  status = 301

[[redirects]]  
  from = "/robots"
  to = "/robots.txt"
  status = 301

# Redirect www to non-www
[[redirects]]
  from = "https://www.kavimukeshgautam.com/*"
  to = "https://kavimukeshgautam.com/:splat"
  status = 301
  force = true

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# SEO and Performance Headers
[[headers]]
  for = "/"
  [headers.values]
    Link = '''</images/Profile.jpeg>; rel=preload; as=image,
              </images/Hero%20sections/*>; rel=preload; as=image'''

# Forms handling (if needed for contact form)
[forms]
  settings = { recipients = ["kavimukeshgautam@gmail.com"] }
